database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  # the JDBC URL
  url: jdbc:h2:mem:test

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

#cloud member settings
cloudMember:
   #set member name
   name: Account

   #set member ip
   ip: 127.0.0.1

   #set member port
   port: 8080

   #set member weight
   weight: 1

   #set member type,like http,https or socket,web-socket
   type: http

#cloud url settings,user ; if have multi
cloudUrl: http://23.83.241.91:4001